services:
  jupyter:
    # image: quay.io/jupyter/datascience-notebook
    image: vinhtranthai/jupyter-notebook-papermill
    user: "0:0"
    volumes:
      - .:/home/jovyan/work
    ports:
      - 8888:8888
    container_name: jupyter_notebook
    restart: always
