volumes:
  etc_wireguard:

services:
  wg-easy:
    image: ghcr.io/wg-easy/wg-easy:15
    container_name: wg-easy

    environment:
      - WG_HOST=178.128.120.74   # Public IP or domain name
      - WG_PORT=51820                 # VPN UDP port
      - WG_UI_PORT=51821
      - WG_INSECURE=true
      - WG_PASSWORD=password
      - WG_USERNAME=admin
      - WG_ALLOWED_IPS=0.0.0.0/0
      - WG_DISABLE_IPV6=true

    networks:
      wg:
        ipv4_address: 10.42.42.42

    volumes:
      - etc_wireguard:/etc/wireguard
      - /lib/modules:/lib/modules:ro

    ports:
      - "51820:51820/udp"
      - "51821:51821/tcp"

    restart: unless-stopped

    cap_add:
      - NET_ADMIN
      - SYS_MODULE

    sysctls:
      - net.ipv4.ip_forward=1
      - net.ipv4.conf.all.src_valid_mark=1
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.default.forwarding=1

networks:
  wg:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 10.42.42.0/24

