services:
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API port
      - "9001:9001"   # MinIO Console (UI) port
    volumes:
      - minio-data:/data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: miniopassword
    command: server --console-address ":9001" /data
    restart: always

volumes:
  minio-data: